# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2SZpussZcIJNfZK1v7-xvInumtttuVY
"""

szdef create(notes):
    print('Введите текст для заметки:')
    note = input()
    notes.append(note)
    with open('bd.txt', 'a', encoding="utf-8") as f:
        f.write(note + "\n")
    print('Заметка добавлена')


def delete(notes):
    print('Введите номер заметки, которую надо удалить:')
    index = int(input())
    if 1 <= index <= len(notes):
        del notes[index - 1]
        with open('bd.txt', "w", encoding="utf-8") as f:
            for n in notes:
                f.write(n + "\n")
        print("Заметка удалена.")
    else:
        print("Неверный номер заметки.")
    return notes


def search(notes):
    print('Введите заметку (ключевое слово) для поиска:')
    keyword = input().lower()
    found_notes = [note for note in notes if keyword in note.lower()]
    if not found_notes:
        print("Заметка не найдена.")
    else:
        print("Найденные заметки:")
        for i, note in enumerate(found_notes):
            print(f"{i + 1}. {note}")


def close(notes):
    print('До свидания!')
    with open('bd.txt', "w", encoding="utf-8") as f:
        for n in notes:
            f.write(n + "\n")
    exit()


def show(notes):
    if not notes:
        print("Нет доступных заметок.")
    else:
        print("Ваши заметки:")
        for i, note in enumerate(notes):
            print(f"{i + 1}. {note}")


# интерфейс
def interface():
    try:
        with open('bd.txt', "r", encoding="utf-8") as f:
            notes = [line.strip() for line in f]
    except FileNotFoundError:
        notes = []

    print('Здравствуй, пользователь! Это менеджер твоих заметок.')
    while True:
        print('''Вот список доступных команд:
    1) создать заметку
    2) удалить заметку
    3) поиск заметки
    4) закрыть менеджер
    5) показать заметки
    Введите номер выбранной команды:''')
        answer = input()
        match answer:
            case '1':
                create(notes)
            case '2':
                delete(notes)
            case '3':
                search(notes)
            case '4':
                close(notes)
            case '5':
                show(notes)
            case _:
                print('Введены некорректные данные')
                continue


interface()